### ISSUE TITLE
Release Schedule: Minor improvements and bug fixes (v4.7.0)

### ISSUE THREAD

**Issue by sumibin** [Snapmaker/Luban#1991]
## Estimate Release Date

2023.03.07-> 2023.03.14 (Based on the test results, Workspace has a lot of problems)

## Feature Request
- [x] Feature Request: Scaling model by dimension (mm) #1993
- [x] Feature Request: Hover tips of unlink parameter
- [x] [Feature Request: Dual extruder material length & weight estimate#1916](https://github.com/Snapmaker/Luban/issues/1916)
## BUG
- [x] [BUG: Exceptional slicing failure on Windows11 and macOS](https://github.com/Snapmaker/Luban/issues/1957) 
- [x] #2018 
- [x] #2019 
- [x] [Bug: open project error in 3d printing #2002](https://github.com/Snapmaker/Luban/issues/2002)
- [x] [BUG: Machine definition populate](https://github.com/orgs/Snapmaker/projects/1/views/2?pane=issue&itemId=21044049)
- [x] [BUG: J1&Artisan&SM2.0 Dual serial connect error#1988](https://github.com/Snapmaker/Luban/issues/1988)
- [x] [BUG: Loading object block when right panel loading#1990](https://github.com/Snapmaker/Luban/issues/1990)
- [x] [BUG: Original connect info error#1989](https://github.com/Snapmaker/Luban/issues/1989)
- [x] [Bug: When printing online, the "time remaining" display in the job status is faulty#1901](https://github.com/Snapmaker/Luban/issues/1901)
- [x] [Bug: Dual extruder settings for single-extruder setup in 3d printing#2001](https://github.com/Snapmaker/Luban/issues/2001)
- [x] [Bug: Default stop height parameter in CNC is too small#2004](https://github.com/Snapmaker/Luban/issues/2004)
- [x] [Bug: Close automatically without any operation when saving project#2006](https://github.com/Snapmaker/Luban/issues/2006)

## Unfinished(next version)
- [ ] #1919 
- [ ] Refactor: Console widget restore
- [ ] #1960 
- [ ] #2008 
- [ ] #2011 
- [ ] [BUG: Synchronize nozzle diameter will change the wrong nozzle size#1987](https://github.com/Snapmaker/Luban/issues/1987)
- [ ] [Bug: Can't continue to cut if enclosure door was open when starting in Laser#1844](https://github.com/Snapmaker/Luban/issues/1844)
- [ ] [Bug: Stuck infinitely after homing in 3d printing#1771](https://github.com/Snapmaker/Luban/issues/1771)
- [ ] [Bug: Excess path when laser cuts multiple times#1995](https://github.com/Snapmaker/Luban/issues/1995)
- [ ] [Bug: line width is ignored in 3d printing (extruder settings do not follow Luban UI settings in print profiles)#1899](https://github.com/Snapmaker/Luban/issues/1899)
